name: Unambiguous System Architecture
baseurl: '/CEACIDE/jellyfish'
ceacide_latest_release_endpoint: 'https://github.ms.northgrum.com/api/v3/repos/CEACIDE/jellyfish/releases/latest'

# collections:
#   books:
#     output: true

defaults:
  - scope:
      path: 'books/*'
    values:
      layout: 'book'

  - scope:
      path: '' # all files in the project
    values:
      layout: 'default'
